"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _article_content from './article-content.bones.json'

registerBones({
  "article-content": _article_content,
})
