"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _pin_panel_multi from './pin-panel-multi.bones.json'
import _trip_panel from './trip-panel.bones.json'
import _timeline_strip from './timeline-strip.bones.json'
import _trip_list_default from './trip-list-default.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","darkColor":"rgba(255,255,255,0.08)","animate":"pulse"})

registerBones({
  "pin-panel-multi": _pin_panel_multi,
  "trip-panel": _trip_panel,
  "timeline-strip": _timeline_strip,
  "trip-list-default": _trip_list_default,
})
